// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvmK4Rwmla06S4q06D5uDCvPfZfJD1iPE',
    appId: '1:734204761518:web:e656356d1ac7959030a43f',
    messagingSenderId: '734204761518',
    projectId: 'my-flutter-app-237a7',
    authDomain: 'my-flutter-app-237a7.firebaseapp.com',
    storageBucket: 'my-flutter-app-237a7.firebasestorage.app',
    measurementId: 'G-FGSN6D6WB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCiuZlywYLQUxI2MJvT2Y4DgVETWObS8s',
    appId: '1:734204761518:android:7a65c1eb6d1d8cd330a43f',
    messagingSenderId: '734204761518',
    projectId: 'my-flutter-app-237a7',
    storageBucket: 'my-flutter-app-237a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTVm4_LVBYjN-lSN4jGgK9sxXXqRb9Zi4',
    appId: '1:734204761518:ios:c5e4b324dccc160430a43f',
    messagingSenderId: '734204761518',
    projectId: 'my-flutter-app-237a7',
    storageBucket: 'my-flutter-app-237a7.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTVm4_LVBYjN-lSN4jGgK9sxXXqRb9Zi4',
    appId: '1:734204761518:ios:c5e4b324dccc160430a43f',
    messagingSenderId: '734204761518',
    projectId: 'my-flutter-app-237a7',
    storageBucket: 'my-flutter-app-237a7.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvmK4Rwmla06S4q06D5uDCvPfZfJD1iPE',
    appId: '1:734204761518:web:539315f4dbbb9f8330a43f',
    messagingSenderId: '734204761518',
    projectId: 'my-flutter-app-237a7',
    authDomain: 'my-flutter-app-237a7.firebaseapp.com',
    storageBucket: 'my-flutter-app-237a7.firebasestorage.app',
    measurementId: 'G-Y09L8TLG6Y',
  );
}
